{% extends 'layout.swig' %}

{% block content %}
  <h1>{{ title }}</h1>
  <p>Welcome, this is very early work in progress</p>
  <p> Give <a href='/api/@bradoyler'>My Medium user page</a> a try</p>
  <p> And then, a <a href='/api/@bradoyler/ec63092e3865'>Medium post</a></p>

  <p>Protip: install the
  <a href='https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en'>JSONView Chrome extension</a></p>
  <h4>Enjoy!</h4>
{% endblock %}
