{% extends 'layout.swig' %}

{% block content %}
  <h1>Medium alt-render</h1>
  <p>Welcome, this is a work in progress</p>
  <hr>
  <h2>API output: </h2>
  <p>Give <a href='/api/@bradoyler'>my Medium user page</a> a try</p>
  <p><a href='/api/@bradoyler/ec63092e3865'>A post on Medium</a></p>
  <hr>
  <h2>Rendering demos: </h2>
  <p><a href='/demo/@bradoyler/ec63092e3865'>A post on Medium </a></p>

  <hr>
  <h4>Enjoy!</h4>

{% endblock %}
